# -*- coding: utf-8 -*-
"""Question 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJ5fPaftQFKl7tYIE-i5tLsHFq6lkd4J
"""

import csv
import os
import heapq
import matplotlib.pyplot as plt

for density in [10, 20, 30]:

    filename = f"grid_{density}pct.csv"

    print("\nTesting:", filename)

    if not os.path.exists(filename):
        print("ERROR: Dataset not found!")
        continue

    with open(filename, "r") as f:
        grid = [[int(x) for x in row] for row in csv.reader(f)]

    print("Grid size:", len(grid), "x", len(grid[0]))

    obstacles = sum(sum(row) for row in grid)
    print("Actual obstacle density:",
          round(obstacles / 4900 * 100, 2), "%")

    start = (0, 0)
    goal = (69, 69)

    # Check whether a path exists using BFS
    queue = [start]
    visited = {start}
    parent = {start: None}

    while queue:

        r, c = queue.pop(0)

        if (r, c) == goal:
            break

        for dr, dc in [(1,0), (-1,0), (0,1), (0,-1)]:

            nr, nc = r + dr, c + dc

            if (0 <= nr < 70 and 0 <= nc < 70
                and grid[nr][nc] == 0
                and (nr, nc) not in visited):

                visited.add((nr, nc))
                parent[(nr, nc)] = (r, c)
                queue.append((nr, nc))

    if goal in visited:

        path = []
        node = goal

        while node is not None:
            path.append(node)
            node = parent[node]

        path.reverse()

        print("PATH FOUND!")
        print("Path length:", len(path) - 1)

        plt.figure(figsize=(8, 8))
        plt.imshow(grid, cmap="gray_r", origin="upper")

        plt.plot(
            [p[1] for p in path],
            [p[0] for p in path],
            color="red",
            linewidth=3
        )

        plt.scatter(0, 0, color="lime", s=100)
        plt.scatter(69, 69, color="blue", s=100, marker="*")

        plt.title(f"{density}% Obstacles - Path Verified")
        plt.show()

    else:
        print("NO PATH EXISTS IN THIS CSV!")