# -*- coding: utf-8 -*-
"""Assignment2 Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4k1r9cyrdfXB4gEMWfLwxKg3JUKATCO
"""

import csv
import heapq
import time

# Load city road dataset
def load_graph(filename):

    graph = {}

    with open(filename, "r", encoding="utf-8-sig") as file:

        reader = csv.DictReader(file)

        for row in reader:

            city1 = row["Origin"].strip().title()
            city2 = row["Destination"].strip().title()
            distance = float(row["Distance"])

            # Add roads in both directions
            graph.setdefault(city1, []).append((city2, distance))
            graph.setdefault(city2, []).append((city1, distance))

    return graph


# Dijkstra algorithm
def dijkstra(graph, start):

    distances = {city: float("inf") for city in graph}
    parent = {city: None for city in graph}

    distances[start] = 0

    priority_queue = [(0, start)]

    visited = set()

    while priority_queue:

        current_distance, current_city = heapq.heappop(priority_queue)

        if current_city in visited:
            continue

        visited.add(current_city)

        for neighbour, weight in graph[current_city]:

            new_distance = current_distance + weight

            if new_distance < distances[neighbour]:

                distances[neighbour] = new_distance
                parent[neighbour] = current_city

                heapq.heappush(
                    priority_queue,
                    (new_distance, neighbour)
                )

    return distances, parent


# Display route
def get_path(parent, destination):

    path = []
    current = destination

    while current is not None:

        path.append(current)
        current = parent[current]

    return " -> ".join(path[::-1])


# Main program
filename = "indian-cities-dataset.csv"

graph = load_graph(filename)

print("Available Cities:")
print(", ".join(sorted(graph.keys())))

start = input("\nEnter starting city: ").strip().title()

if start not in graph:

    print("City not found in dataset.")

else:

    start_time = time.perf_counter()

    distances, parent = dijkstra(graph, start)

    end_time = time.perf_counter()

    print("\n===== SHORTEST PATH RESULTS =====")

    for city in sorted(graph):

        if distances[city] == float("inf"):

            print(city, ": Not reachable")

        else:

            print("\nDestination:", city)
            print("Distance:", distances[city], "km")
            print("Path:", get_path(parent, city))

    print("\nExecution Time:",
          round(end_time - start_time, 6), "seconds")