# -*- coding: utf-8 -*-
"""Question 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUrg22xDj_KsTeGFdSVVSTfMjSvOl2ff
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import heapq
import time
from google.colab import files

# Upload dataset
uploaded = files.upload()
filename = list(uploaded.keys())[0]

actual_grid = pd.read_csv(filename, header=None).values.astype(int)

ROWS, COLS = actual_grid.shape
START = (0, 0)
GOAL = (ROWS - 1, COLS - 1)

# 0 = Free, 1 = Obstacle, -1 = Unknown
known_grid = np.full((ROWS, COLS), -1)

# A* algorithm
def astar(grid, start, goal):
    rows, cols = grid.shape

    pq = []
    heapq.heappush(pq, (0, start))

    parent = {}
    g_score = {start: 0}
    visited = set()
    nodes_explored = 0

    while pq:
        _, current = heapq.heappop(pq)

        if current in visited:
            continue

        visited.add(current)
        nodes_explored += 1

        if current == goal:
            path = [current]

            while current in parent:
                current = parent[current]
                path.append(current)

            return path[::-1], nodes_explored

        r, c = current

        for dr, dc in [(1,0), (-1,0), (0,1), (0,-1)]:
            nr, nc = r + dr, c + dc

            if 0 <= nr < rows and 0 <= nc < cols:

                # Unknown cells are temporarily assumed free
                if grid[nr, nc] == 1:
                    continue

                neighbor = (nr, nc)
                new_cost = g_score[current] + 1

                if new_cost < g_score.get(neighbor, float('inf')):
                    g_score[neighbor] = new_cost
                    parent[neighbor] = current

                    h = abs(nr - goal[0]) + abs(nc - goal[1])

                    heapq.heappush(
                        pq, (new_cost + h, neighbor)
                    )

    return None, nodes_explored


# Initial plan using completely unknown map
initial_map = np.zeros((ROWS, COLS), dtype=int)

initial_path, _ = astar(initial_map, START, GOAL)

# Add a hidden obstacle on the initial route.
# The UGV does not know about this obstacle initially.
obstacle_position = initial_path[min(8, len(initial_path) - 2)]
actual_grid[obstacle_position] = 1

# Sensor: observe nearby 3x3 area
def sense(position):
    r, c = position

    for dr in range(-1, 2):
        for dc in range(-1, 2):
            nr, nc = r + dr, c + dc

            if 0 <= nr < ROWS and 0 <= nc < COLS:
                known_grid[nr, nc] = actual_grid[nr, nc]


# UGV navigation
current = START
travelled_path = [START]

replanning_count = 0
total_explored = 0

start_time = time.time()

path, explored = astar(known_grid, current, GOAL)
total_explored += explored

max_steps = ROWS * COLS * 4

for step in range(max_steps):

    if current == GOAL:
        break

    # Detect nearby obstacles
    sense(current)

    # Check whether a newly discovered obstacle blocks the route
    blocked = any(
        known_grid[r, c] == 1
        for r, c in path[1:]
    )

    if blocked:
        path, explored = astar(known_grid, current, GOAL)
        total_explored += explored
        replanning_count += 1

        if path is None:
            print("No path available!")
            break

    # Move one step along the planned route
    next_position = path[1]

    # Safety check
    if actual_grid[next_position] == 1:
        known_grid[next_position] = 1

        path, explored = astar(known_grid, current, GOAL)
        total_explored += explored
        replanning_count += 1

        if path is None:
            print("No alternate path!")
            break

        continue

    current = next_position
    travelled_path.append(current)

    path = path[1:]

execution_time = time.time() - start_time

# Results
print("========== Q3 RESULTS ==========")
print("Goal Status:", "Success" if current == GOAL else "Failed")
print("Travel Distance:", len(travelled_path) - 1, "moves")
print("Replanning Count:", replanning_count)
print("Total Nodes Explored:", total_explored)
print("Execution Time:", round(execution_time, 5), "seconds")


# Visualization
plt.figure(figsize=(10, 9))

# Unknown cells gray, free cells white, obstacles black
plt.imshow(known_grid, cmap="gray_r", vmin=-1, vmax=1)

path_rows = [p[0] for p in travelled_path]
path_cols = [p[1] for p in travelled_path]

plt.plot(path_cols, path_rows, 'r-', linewidth=2, label="UGV Travelled Path")

plt.scatter(START[1], START[0], c='lime', s=100,
            edgecolors='black', label='Start', zorder=5)

plt.scatter(GOAL[1], GOAL[0], c='blue', marker='*',
            s=180, label='Goal', zorder=5)

plt.title("UGV Navigation with Unknown Obstacles and Replanning")
plt.xlabel("Column")
plt.ylabel("Row")
plt.legend()
plt.grid(False)
plt.show()


# Save results
results = pd.DataFrame([{
    "Goal Status": "Success" if current == GOAL else "Failed",
    "Travel Distance": len(travelled_path) - 1,
    "Replanning Count": replanning_count,
    "Total Nodes Explored": total_explored,
    "Execution Time": execution_time
}])

results.to_csv("Q3_results.csv", index=False)
pd.DataFrame(known_grid).to_csv("Q3_discovered_map.csv", index=False)

print("\nFiles saved successfully!")
files.download("Q3_results.csv")
files.download("Q3_discovered_map.csv")